name: Full CI/CD for AI Comic Generator

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Code Linting (black & flake8)
      run: |
        pip install black flake8
        black --check backend/ worker/ pdf/
        flake8 backend/ worker/ pdf/ --max-line-length=120

    - name: Docker Compose Build
      run: docker compose build

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-comic-backend:latest

    - name: Push Worker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.worker
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-comic-worker:latest

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/ai-video2comic
          git pull
          docker compose down
          docker compose pull
          docker compose up -d
